### ISSUE TITLE
Initialize function should be named NewDevice()

### ISSUE THREAD

**Issue by deadprogram** [aykevl/tinygo-drivers#1]
Shouldn't the initialize function be named `NewDevice()`? 

IMO `NewI2C()` sounds more like what would initialize the bus, not the device.

EDIT: perhaps we should name it `NewI2CDevice()` for when other protocol devices are added, for example `NewSPIDevice()`.

**Comment by aykevl** [comment]
I checked periph and it uses both [NewI2C](https://godoc.org/periph.io/x/periph/devices/cap1xxx#NewI2C) and [New](https://godoc.org/periph.io/x/periph/devices/ds248x#New). It would be nice to follow that convention. Of course, I'd love to integrate all these drivers into periph at some point, but for now I would just want to match the conventions.

@maruel what do you think of the naming convention?

Somewhat related: maybe `Device` should be renamed to `Dev` in this repository. And that should be done early to avoid too much breakage.

**Comment by deadprogram** [comment]
I was thinking the opposite: keep drivers in THIS repo, with the idea that various frameworks/libs could all use them. 

Possibly then migrate drivers from other projects here, and then just provide thin wrappers to use in other contexts.

In any case, I still prefer `NewI2CDevice()` over either`NewI2C()` or `NewDevice()`. I'd also prefer to avoid `Dev` as abbreviations can be confusing.

**Comment by maruel** [comment]
In periph, there's one package per device driver. The rationale is:
1. This simplifies unit test coverage, it's easy to determine if a specific device driver is covered at 100% via `go test -cover`.
1. It makes referring to symbols in the driver look like `pkg.X`, which I find appropriate. For example `bmxx80.Opts`.
1. A device doesn't _belong_ to a protocol, the protocol is a mean to access a device. IMHO `spi.NewAPA102()` makes less sense than `apa102.New()`.
    1. This is even more serious in the case of the lepton, which requires simultaneous I2C and SPI links.
1. It enables support for device drivers accessible via multiple protocol, notoriously ssd1306, BME280, CAP1188. In this case, we *need* to have different functions for each protocol.

Now to answer the initial question: the later point explains why some drivers use `New()` while others use `New<Protocol>()`, where Protocol is generally I2C or SPI. The form NewI2C should be the *exception*, not the norm. So the NewI2C/NewSPI form is *only* used when a device can be accessed via multiple protocols. This  cap1xxx is looks weird because only I2C is currently implemented, and SPI is not yet done, but that's just because we didn't take the time yet. That explains why the function is named NewI2C and not New. But for "normal" devices supporting a single protocol, "New" should be used.

I _intentionally_ wrote initial periph's drivers primarily for devices that were multi-protocols to work out the kinks. That's why you'll find so many NewI2C/NewSPI.

As for Dev, I standardized on it as I didn't feel it being ambiguous, the drivers design in a fully qualified style of `pkg.Dev`. Since it's returned by New(), it's fairly coherent. Since there's one device per package, there's no ambiguity. And most importantly I wanted to avoid stuttering.

**Comment by deadprogram** [comment]
OK, then let's go with `func New(bus machine.I2C) Device` per package, with one `Device` defined per package.

**Comment by aykevl** [comment]
> OK, then let's go with `func New(bus machine.I2C) Device` per package, with one `Device` defined per package.

Sounds good! You can make a PR, or else I can fix it the next time I'm working on this package.

Regarding the split into packages: yes, I think splitting this way makes a lot of sense.
